version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1G
        reservations:
          cpus: 0
          memory: 0M
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    environment:
      - TZ=$TIME_ZONE
    volumes:
      - .:/srv/app
      - /srv/app/node_modules
    links:
      - mysql
  mysql:
    image: mysql:5.7
    env_file: .env
    volumes:
      - certika:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - TZ=$TIME_ZONE
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
volumes:
  certika:
